### ISSUE TITLE
Bot Big No Brainer - Definition of Input Matricies 

### ISSUE THREAD

**Issue by dgcrox** [OrsoEric/kaggle-Lux-AI#16]
Define the input matrices structure

**Comment by dgcrox** [comment]
The input matrices will be always  32x32, in case of a smaller playground the outside  tiles will be set to 0

There are 8 matrices:

1. Cities matrix: every tile has a value of +fuel+1 for bot's cities and -fuel-1 for  opponent's cities
2. Workers matrix: every tile has  a value of +resources+1 for boot's  workers and -resources-1 for opponent's ones
3. Cart matrix: as workers matrix
4. Road matrix: road value per tile
5. Wood matrix: amount of wood per tile
6. Coal matrix: as wood
7. Uranium matrix: as wood
8. Cooldown matrix: Bot's cooldown with negative sign, opponent's cooldown positive

this matrices are meant to give the bot the spatial representation of the map and will be hopefully fed into a convolutional network

There will be also a vector that will skip the convolutional network and fed directly to the main net. This vector will contain:

- Turn number
- Bot's research
- Opponent's research
- Coal unlocked bot: bool
- Coal unlocked opponent: bool
- Uranium unlocked bot: bool
- Uranium unlocked opponent: bool
- [optional] day/night bool
- [optional] total values of workers, cities, carts, fuel of each side
- [optional] fuel needed to survive night
- [optional] resource output

This representation has been chosen to retain the most information possible, but some matrices can be combined (e.g. a single matrix for the 3 resources, or a single matrix for carts and workers) to reduce the input dimension if the bot  will have convergence or calculation time problems.

**Comment by dgcrox** [comment]
Possible evolutions:

- introduce FOM matrices (e.g. city danger matrix)
- split  existence/resources matrices for units

**Comment by OrsoEric** [comment]
np.darray (8,32,32) with indexes held into Perception.E_INPUT_STATUS_VECTOR

A module construct a gif of the input matricies from a Game() class. The gif below is made by compiling the Game() states every 50 turns of the rule based clusterbot L16H7
![Input Matricies](https://raw.githubusercontent.com/OrsoEric/kaggle-Lux-AI/develop/readme_media/2021-10-09-perception.gif)

**Comment by dgcrox** [comment]
**Normalizations**

1. Cities: divide by 2000
2. Workers: divide by 100
3. Carts: divide by 2000
4. Road: divide by 6
5. Wood: divide by 500
6. Coal: divide by 250
7. Uranium: divide by 250
8. Cooldown: divide by 11

The cities matrix can be rethinked (e.g. fuel needet until final dawn, "risk factor", others)

**Comment by OrsoEric** [comment]
![27879876](https://raw.githubusercontent.com/OrsoEric/kaggle-Lux-AI/develop/replays/27879876.gif)

**Comment by OrsoEric** [comment]
Suggestions: @dgcrox 
FOM metrics to tell the BNB how the game is going:

FUEL: due to collection/conversion rates, wood is efficient in city construction, inefficient as fuel. uranium is efficient as fuel inefficient at city construction. The net may need metrics to help understand that spending wood for construction is good, spending uranium for fuel is good.
- How much fuel has been spent in light maintenance (last turn, this night, all game)
- How much fuel is needed to maintain city if nothing change (next turn, this night, until end of game)
- How many resources units have spent in light maintenance (last turn, this night, all game)
- How many resources have been spent in building city, wood, coal and uranium.

ROADS
- How many roads have been built pillaged (last turn, all game)
- How many citytiles/units have been built, have disapperared

TRANSFERS There are emergent properties with transfers that allow transfering in a chain many tiles in a single turn if the ID of units are in increasing order. Walling resources is good to deny resource to enemies. Transfering resources from a resouce enclave cluster out to be used to enlarge a city, might be a power strategy. Some metrics may be needed to give a chance to the net to learn this strategy
- How many resources have been transfered
- Highligt units for whom chain transfer is possible
![Chain Transfer](https://user-images.githubusercontent.com/30684972/136685416-074d6962-c63b-4350-9b2b-368cf2d198ee.png)
